/* eslint-disable @typescript-eslint/no-unsafe-member-access */

export const providers = [
  {
    name: "zalando",
    fullname: "Zalando",
    url: "https://www.zalando.com",
    regions: ["All"],
    isPhotoAnalysisSupported: true,
    isSupported: true,
  },
  {
    name: "vinted",
    fullname: "Vinted",
    url: "https://www.vinted.com",
    regions: ["All"],
    isPhotoAnalysisSupported: true,
    isSupported: true,
  },
  {
    name: "hm",
    fullname: "H&M",
    url: "https://www2.hm.com",
    regions: ["All"],
    isPhotoAnalysisSupported: true,
    isSupported: true,
  },
  {
    name: "bershka",
    fullname: "Bershka",
    url: "https://www.bershka.com",
    regions: ["All"],
    isPhotoAnalysisSupported: true,
    isSupported: true,
  },
  {
    name: "cropp",
    fullname: "Cropp",
    url: "https://www.cropp.com",
    regions: ["All"],
    isPhotoAnalysisSupported: true,
    isSupported: true,
  },
  {
    name: "gucci",
    fullname: "Gucci",
    url: "https://www.gucci.com",
    regions: ["All"],
    isPhotoAnalysisSupported: true,
    isSupported: true,
  },
  {
    name: "prada",
    fullname: "Prada",
    url: "https://www.prada.com",
    regions: ["All"],
    isPhotoAnalysisSupported: true,
    isSupported: true,
  },
  {
    name: "pullandbear",
    fullname: "Pull&Bear",
    url: "https://www.pullandbear.com",
    regions: ["All"],
    isPhotoAnalysisSupported: true,
    isSupported: true,
  },
  {
    name: "stradivarius",
    fullname: "Stradivarius",
    url: "https://www.stradivarius.com",
    regions: ["All"],
    isPhotoAnalysisSupported: true,
    isSupported: true,
  },
  {
    name: "zara",
    fullname: "Zara",
    url: "https://www.zara.com",
    regions: ["All"],
    isPhotoAnalysisSupported: true,
    isSupported: true,
  },
  {
    name: "vitkac",
    fullname: "Vitkac",
    url: "https://vitkac.com",
    regions: ["All"],
    isPhotoAnalysisSupported: true,
    isSupported: true,
  },
  {
    name: "shein",
    fullname: "Shein",
    url: "https://www.shein.com",
    regions: ["EU"],
    isPhotoAnalysisSupported: true,
    isSupported: true,
  },
  {
    name: "American Apparel",
    fullname: "American Apparel",
    url: "https://www.americanapparel.com",
    regions: ["US"],
    isPhotoAnalysisSupported: false,
    isSupported: true,
  },
  {
    name: "Vans",
    fullname: "Vans",
    url: "https://www.vans.com",
    regions: ["All"],
    isPhotoAnalysisSupported: true,
    isSupported: true,
  },
  {
    name: "Uniqlo",
    fullname: "Uniqlo",
    url: "https://www.uniqlo.com",
    regions: ["All"],
    isPhotoAnalysisSupported: true,
    isSupported: "partially",
  },
  {
    name: "Poshmark",
    fullname: "Poshmark",
    url: "https://www.poshmark.com",
    regions: ["All"],
    isPhotoAnalysisSupported: true,
    isSupported: true,
  },
  {
    name: "Thredup",
    fullname: "Thredup",
    url: "https://www.thredup.com",
    regions: ["All"],
    isPhotoAnalysisSupported: true,
    isSupported: true,
  },
  {
    name: "Etsy",
    fullname: "Etsy",
    url: "https://www.etsy.com",
    regions: ["All"],
    isPhotoAnalysisSupported: true,
    isSupported: true,
  },
  {
    name: "Ebay",
    fullname: "Ebay",
    url: "https://www.ebay.com",
    regions: ["All"],
    isPhotoAnalysisSupported: true,
    isSupported: true,
  },
  {
    name: "Asos",
    fullname: "Asos",
    url: "https://www.asos.com",
    regions: ["All"],
    isPhotoAnalysisSupported: true,
    isSupported: true,
  },
  {
    name: "Vestiaire Collective",
    fullname: "Vestiaire Collective",
    url: "https://www.vestiairecollective.com",
    regions: ["All"],
    isPhotoAnalysisSupported: false,
    isSupported: "partially",
  },
] as const;

export type Merchant = {
  name: string;
  fullname: string;
  url: string;
  regions: string[] | null;
  isPhotoAnalysisSupported: boolean;
  isSupported: boolean | "partially";
};
