name: Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Create .env file
      uses: SpicyPizza/create-envfile@v2.0.3
      with:
        envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
        envkey_E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
        envkey_E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
        envkey_KINDE_CLIENT_ID: ${{ secrets.KINDE_CLIENT_ID }}
        envkey_KINDE_CLIENT_SECRET: ${{ secrets.KINDE_CLIENT_SECRET }}
        envkey_KINDE_ISSUER_URL: ${{ secrets.KINDE_ISSUER_URL }}
        envkey_KINDE_POST_LOGIN_REDIRECT_URL: ${{ secrets.KINDE_POST_LOGIN_REDIRECT_URL }}
        envkey_KINDE_POST_LOGOUT_REDIRECT_URL: ${{ secrets.KINDE_POST_LOGOUT_REDIRECT_URL }}
        envkey_KINDE_SITE_URL: ${{ secrets.KINDE_SITE_URL }}
        envkey_SKIP_ENV_VALIDATION: true
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - name: Run Vitest tests
      run: vitest
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
