name: Main
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: "Create env file"
        run: |
          touch apps/www/.env
          echo SKIP_ENV_VALIDATION="true" >> apps/www/.env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> apps/www/.env
          echo DATABASE_URL_NON_POOLING=${{ secrets.DATABASE_URL_NON_POOLING }} >> apps/www/.env
          echo E2E_PASSWORD=${{ secrets.E2E_PASSWORD }} >> apps/www/.env
          echo E2E_USERNAME=${{ secrets.E2E_USERNAME }} >> apps/www/.env
          echo KINDE_CLIENT_ID=${{ secrets.KINDE_CLIENT_ID }} >> apps/www/.env
          echo KINDE_CLIENT_SECRET=${{ secrets.KINDE_CLIENT_SECRET }} >> apps/www/.env
          echo KINDE_ISSUER_URL=${{ secrets.KINDE_ISSUER_URL }} >> apps/www/.env
          echo KINDE_POST_LOGIN_REDIRECT_URL=${{ secrets.KINDE_POST_LOGIN_REDIRECT_URL }} >> apps/www/.env
          echo KINDE_POST_LOGOUT_REDIRECT_URL=${{ secrets.KINDE_POST_LOGOUT_REDIRECT_URL }} >> apps/www/.env
          echo KINDE_SITE_URL=${{ secrets.KINDE_SITE_URL }} >> apps/www/.env
          echo UPLOADCARE_PUBLIC_KEY=${{ secrets.UPLOADCARE_PUBLIC_KEY }} >> apps/www/.env
          echo SPATULA_URL=${{ secrets.SPATULA_URL }} >> apps/www/.env
          echo SPATULA_API_KEY=${{ secrets.SPATULA_API_KEY }} >> apps/www/.env
          cat apps/www/.env
      - name: Install dependencies
        run: npm ci --workspace apps/www --force
      - name: Generate Prisma
        run: npm run www:db:generate
      - name: Push Prisma
        run: npm run www:db:push
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
